extends:
  - stylelint-config-standard
  - stylelint-config-recess-order

rules:
  # General
  indentation: tab
  max-empty-lines: 2
  max-line-length: 80

  # Empty lines
  selector-list-comma-newline-after: always-multi-line
  at-rule-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - blockless-after-same-name-blockless
        - after-comment

  # Strings, Numbers and Units
  length-zero-no-unit:
    - true
    - ignore: [custom-properties]
      ignoreFunctions: [calc]
  number-leading-zero: never
  string-quotes: single

  # Colors
  hue-degree-notation: number
  alpha-value-notation: number

  # Other
  no-duplicate-selectors: null
  no-irregular-whitespace: null

overrides:
  - files: ['*.scss', '**/*.scss']
    extends: stylelint-config-standard-scss
    rules:
      scss/dollar-variable-empty-line-before:
        - always
        - except:
            - first-nested
          ignore:
            - after-comment
            - after-dollar-variable
            - inside-single-line-block

  # redefining global functions is okay
  - files: ['lib/**/*.scss']
    rules:
      scss/no-global-function-names: null

  # less care about generated files and fixtures
  - files: ['**/space.css', '**/fixtures.css']
    rules:
      max-line-length: null

  # allowing `@media` class names
  - files: ['media/**']
    rules:
      selector-class-pattern: ^@?([a-z][a-z0-9]*)(-[a-z0-9]+)*$
