extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
  - '@stylistic/stylelint-config'

rules:
  # General
  '@stylistic/indentation':
    - tab
    - indentInsideParens: once-at-root-twice-in-block
  '@stylistic/max-empty-lines': 2
  '@stylistic/max-line-length': 80

  # Empty lines
  '@stylistic/declaration-colon-newline-after': null
  '@stylistic/declaration-colon-space-after': null
  '@stylistic/function-parentheses-newline-inside': null
  '@stylistic/selector-list-comma-newline-after': null
  at-rule-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - blockless-after-same-name-blockless
        - after-comment

  # Strings, Numbers and Units
  '@stylistic/number-leading-zero': never
  '@stylistic/number-no-trailing-zeros': null
  '@stylistic/string-quotes': single
  length-zero-no-unit:
    - true
    - ignore: [custom-properties]
      ignoreFunctions: [calc]

  # Colors
  alpha-value-notation: number

  # Not suitable for the library of this kind
  declaration-block-no-redundant-longhand-properties: null
  no-duplicate-selectors: null
  no-irregular-whitespace: null

overrides:
  - files: ['*.scss', '**/*.scss']
    extends: stylelint-config-standard-scss
    rules:
      scss/dollar-variable-empty-line-before:
        - always
        - except:
            - first-nested
          ignore:
            - after-comment
            - after-dollar-variable
            - inside-single-line-block

  # redefining global functions is okay
  - files: ['lib/**/*.scss']
    rules:
      scss/no-global-function-names: null

  # less care about generated files and fixtures
  - files: ['**/fixtures.css']
    rules:
      '@stylistic/max-line-length': null

  # allowing `@media` class names
  - files: ['media/**']
    rules:
      selector-class-pattern: ^@?([a-z][a-z0-9]*)(-[a-z0-9]+)*$
